[workspace]
resolver = "2"
members = ["crates/gpui-ghostty"]

[workspace.package]
version = "0.1.7"
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/behzade/gpui-libghostty"

[workspace.dependencies]
async-channel = "2.5"
gpui = { version = "0.2.2", git = "https://github.com/zed-industries/zed", rev = "cc053a4a6fa2fd0e8793201ed9099466af1be0b1" }
libc = "0.2"
raw-window-handle = "0.6"
wait-timeout = "0.2.1"

[workspace.lints.rust]
unsafe_code = "forbid"
unused_must_use = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
dbg_macro = "deny"
print_stderr = "deny"
print_stdout = "deny"
unwrap_used = "deny"
